name: Create Repository Zip Artifact

on:
  push:
    branches: [ "release/*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress repository
        run: zip -r those-under-mountains.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: those-under-mountains.zip
          retention-days: 5